name: revived
description: A simple mockup for a clothing app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.7.0
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  riverpod: ^2.6.1
  uuid: ^4.5.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.3.2
  build_runner: ^2.4.11
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/json/
    - assets/png/
    - assets/png/banners/
    - assets/png/articles/
  fonts:
     - family: OblivianTextLight
       fonts:
         - asset: assets/fonts/oblivian-text-light.otf
     - family: CarmenSansMedium
       fonts:
         - asset: assets/fonts/carmen-sans-medium.ttf
     - family: CarmenSansSemiBold
       fonts:
         - asset: assets/fonts/carmen-sans-semi-bold.ttf
     - family: TypoldBold
       fonts:
         - asset: assets/fonts/typold-bold.otf
